# Generated by Django 5.1 on 2024-08-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField()),
                ('linkedin', models.CharField(max_length=200)),
                ('objective', models.TextField(max_length=500)),
                ('work1', models.CharField(blank=True, max_length=200, null=True)),
                ('work1r', models.CharField(blank=True, max_length=200, null=True)),
                ('work1d', models.TextField(blank=True, max_length=200, null=True)),
                ('work2', models.CharField(blank=True, max_length=200, null=True)),
                ('work2r', models.CharField(blank=True, max_length=200, null=True)),
                ('work2d', models.TextField(blank=True, max_length=200, null=True)),
                ('work3', models.CharField(blank=True, max_length=200, null=True)),
                ('work3r', models.CharField(blank=True, max_length=200, null=True)),
                ('work3d', models.TextField(blank=True, max_length=200, null=True)),
                ('college', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('cgpa', models.FloatField()),
                ('higher', models.CharField(max_length=200)),
                ('higherp', models.FloatField()),
                ('high', models.CharField(max_length=200)),
                ('highp', models.FloatField()),
                ('proj1', models.CharField(blank=True, max_length=200, null=True)),
                ('proj1d', models.TextField(blank=True, max_length=200, null=True)),
                ('proj2', models.CharField(blank=True, max_length=200, null=True)),
                ('proj2d', models.TextField(blank=True, max_length=200, null=True)),
                ('proj3', models.CharField(blank=True, max_length=200, null=True)),
                ('proj3d', models.TextField(blank=True, max_length=200, null=True)),
                ('cert1', models.CharField(max_length=200)),
                ('cert2', models.CharField(max_length=200)),
                ('skills', models.TextField(max_length=300)),
                ('ach1', models.CharField(max_length=200)),
                ('ach2', models.CharField(max_length=200)),
            ],
        ),
    ]
