# Generated by Django 5.1 on 2024-08-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_profile_cgpa_alter_profile_higherp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ach1',
        ),
        migrations.AlterField(
            model_name='profile',
            name='ach2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cert1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cert2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
