# Generated by Django 5.1 on 2024-08-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_profile_ctime_profile_htime_profile_stime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ach1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
